import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Poppins = localFont({
	src: "./fonts/Poppins.ttf",
	variable: "--font-poppins",
	weight: "100",
});

export const metadata: Metadata = {
	title: "Stakeme test",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`  antialiased`}>{children}</body>
		</html>
	);
}
